### ISSUE TITLE
Can't close Cards window

### ISSUE THREAD

**Issue by ghost** [Arthur-Milchior/anki-fast-note-type-editor#1]
I get the following error when I try to close the cards window

Anki 2.1.8 (71e0c880) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\802285486\clayout.py", line 107, in reject
    self.mm.save(self.model, templates=True, oldModel = self.originalModel, newTemplatesData = self.newTemplatesData)
<class 'AttributeError'>: 'CardLayout' object has no attribute 'originalModel'

**Comment by Arthur-Milchior** [comment]
Sorry. I knew this bug. And it seems I totally forgot to upload the correction. It should work now. Let me know if it is not the case.

**Comment by Arthur-Milchior** [comment]
Is this corrected ?

**Comment by ghost** [comment]
Still threw the same bug. I checked and it worked fine with all addons disabled. The addon seems to have a conflict with the [Night Mode](https://ankiweb.net/shared/info/1496166067) addon.

**Comment by Arthur-Milchior** [comment]
Thanks, it certainly help a lot. I don't know how you discovered the correct add-on conflicting. But when I install Night Mode, I have the same error. 
I must admit I still don't understand the bug. Because I don't understand how Night-mode change the card layout. I'm looking at it

**Comment by ghost** [comment]
I just deleted addons from the addon folder in batches of ten until it stopped throwing an error. 
Good luck with the issue.

**Comment by Arthur-Milchior** [comment]
I'll ask for Night Mode's author for some explanation. Right now, I don't even understand how this add-on can work. Even if it clearly works, which makes no sens to me.

**Comment by Arthur-Milchior** [comment]
https://github.com/krassowski/Anki-Night-Mode/issues/60

I'll edit the add-on to state that it's a known compatibility issue.

**Comment by Arthur-Milchior** [comment]
According to Night Mode author, you can go to «View → Night Mode → Choose what to style» and deactivate Night Mode for Clayout. It would solve the problem.

I've no better solution to offer, and honestly I'm not interested in spending more on my free time for it.

**Comment by ghost** [comment]
Thank you. This works for my purposes.

**Comment by Arthur-Milchior** [comment]
I'm editing the readme, in order to warn people about it.
